// Code generated by scripts/gen-model-catalog.mjs from https://models.dev/api.json. DO NOT EDIT.
// Regenerate with: node scripts/gen-model-catalog.mjs
//
// There is deliberately NO CI drift gate for this file: the source is a remote third-party API,
// and a network-dependent CI check would be flaky (the whole gate suite must pass offline).
// Regeneration is a manual, occasional act — run the command above and commit the result.
package config

// CatalogModel is one selectable LLM model entry (SPA model-picker + config surfaces).
type CatalogModel struct {
	ID       string `json:"id"`       // provider-native model id, e.g. the exact string LLM_MODEL takes
	Name     string `json:"name"`     // human display name
	Provider string `json:"provider"` // anthropic | openai | gemini
}

// ModelCatalog lists tool-call-capable chat models from anthropic, openai, and gemini,
// sorted by provider then release date descending. See the generator's header for the
// exclusion rules (non-chat specialist models, deprecated generations, not-yet-released).
var ModelCatalog = []CatalogModel{
	{ID: "claude-opus-5", Name: "Claude Opus 5", Provider: "anthropic"},
	{ID: "claude-sonnet-5", Name: "Claude Sonnet 5", Provider: "anthropic"},
	{ID: "claude-fable-5", Name: "Claude Fable 5", Provider: "anthropic"},
	{ID: "claude-opus-4-8", Name: "Claude Opus 4.8", Provider: "anthropic"},
	{ID: "claude-opus-4-7", Name: "Claude Opus 4.7", Provider: "anthropic"},
	{ID: "claude-sonnet-4-6", Name: "Claude Sonnet 4.6", Provider: "anthropic"},
	{ID: "claude-opus-4-6", Name: "Claude Opus 4.6", Provider: "anthropic"},
	{ID: "claude-opus-4-5", Name: "Claude Opus 4.5 (latest)", Provider: "anthropic"},
	{ID: "claude-opus-4-5-20251101", Name: "Claude Opus 4.5", Provider: "anthropic"},
	{ID: "claude-haiku-4-5-20251001", Name: "Claude Haiku 4.5", Provider: "anthropic"},
	{ID: "claude-haiku-4-5", Name: "Claude Haiku 4.5 (latest)", Provider: "anthropic"},
	{ID: "claude-sonnet-4-5-20250929", Name: "Claude Sonnet 4.5", Provider: "anthropic"},
	{ID: "claude-sonnet-4-5", Name: "Claude Sonnet 4.5 (latest)", Provider: "anthropic"},
	{ID: "gpt-5.6-sol", Name: "GPT-5.6 Sol", Provider: "openai"},
	{ID: "gpt-5.6", Name: "GPT-5.6", Provider: "openai"},
	{ID: "gpt-5.6-luna", Name: "GPT-5.6 Luna", Provider: "openai"},
	{ID: "gpt-5.6-terra", Name: "GPT-5.6 Terra", Provider: "openai"},
	{ID: "gpt-5.5-pro", Name: "GPT-5.5 Pro", Provider: "openai"},
	{ID: "gpt-5.5", Name: "GPT-5.5", Provider: "openai"},
	{ID: "gpt-5.4-mini", Name: "GPT-5.4 mini", Provider: "openai"},
	{ID: "gpt-5.4-nano", Name: "GPT-5.4 nano", Provider: "openai"},
	{ID: "gpt-5.4-pro", Name: "GPT-5.4 Pro", Provider: "openai"},
	{ID: "gpt-5.4", Name: "GPT-5.4", Provider: "openai"},
	{ID: "gpt-5.3-chat-latest", Name: "GPT-5.3 Chat (latest)", Provider: "openai"},
	{ID: "gpt-5.2", Name: "GPT-5.2", Provider: "openai"},
	{ID: "gpt-5.2-chat-latest", Name: "GPT-5.2 Chat", Provider: "openai"},
	{ID: "gpt-5.2-pro", Name: "GPT-5.2 Pro", Provider: "openai"},
	{ID: "gpt-5.1", Name: "GPT-5.1", Provider: "openai"},
	{ID: "gpt-5-pro", Name: "GPT-5 Pro", Provider: "openai"},
	{ID: "gpt-5-nano", Name: "GPT-5 Nano", Provider: "openai"},
	{ID: "gpt-5", Name: "GPT-5", Provider: "openai"},
	{ID: "gpt-5-mini", Name: "GPT-5 Mini", Provider: "openai"},
	{ID: "o3-pro", Name: "o3-pro", Provider: "openai"},
	{ID: "o3", Name: "o3", Provider: "openai"},
	{ID: "o4-mini", Name: "o4-mini", Provider: "openai"},
	{ID: "gpt-4.1-nano", Name: "GPT-4.1 nano", Provider: "openai"},
	{ID: "gpt-4.1", Name: "GPT-4.1", Provider: "openai"},
	{ID: "gpt-4.1-mini", Name: "GPT-4.1 mini", Provider: "openai"},
	{ID: "o1-pro", Name: "o1-pro", Provider: "openai"},
	{ID: "gemini-3.7-flash", Name: "Gemini 3.7 Flash", Provider: "gemini"},
	{ID: "gemini-3.5-flash-lite", Name: "Gemini 3.5 Flash Lite", Provider: "gemini"},
	{ID: "gemini-3.6-flash", Name: "Gemini 3.6 Flash", Provider: "gemini"},
	{ID: "gemini-flash-latest", Name: "Gemini Flash Latest", Provider: "gemini"},
	{ID: "gemini-3.5-flash", Name: "Gemini 3.5 Flash", Provider: "gemini"},
	{ID: "gemini-flash-lite-latest", Name: "Gemini Flash-Lite Latest", Provider: "gemini"},
	{ID: "gemini-3.1-flash-lite", Name: "Gemini 3.1 Flash Lite", Provider: "gemini"},
	{ID: "gemma-4-26b-a4b-it", Name: "Gemma 4 26B A4B IT", Provider: "gemini"},
	{ID: "gemma-4-31b-it", Name: "Gemma 4 31B IT", Provider: "gemini"},
	{ID: "gemini-3.1-flash-lite-preview", Name: "Gemini 3.1 Flash Lite Preview", Provider: "gemini"},
	{ID: "gemini-3.1-pro-preview", Name: "Gemini 3.1 Pro Preview", Provider: "gemini"},
	{ID: "gemini-3-flash-preview", Name: "Gemini 3 Flash Preview", Provider: "gemini"},
	{ID: "gemini-2.5-flash-lite", Name: "Gemini 2.5 Flash-Lite", Provider: "gemini"},
	{ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash", Provider: "gemini"},
	{ID: "gemini-2.5-pro", Name: "Gemini 2.5 Pro", Provider: "gemini"},
}

// CatalogProviders returns the distinct providers present in ModelCatalog, in catalog order.
func CatalogProviders() []string {
	return []string{
		"anthropic",
		"openai",
		"gemini",
	}
}
